postgres:
  host: localhost
  port: 3456
  user: postgres
  password: secure_password
  dbname: postgres
  sslmode: disabled
bot:
  host: localhost
replies:
  default: Default reply
  welcome: Welcome Username
errors:
  default: Unknown Error

