messages:
  responses:
    start: Приветствую, %s
    setup: Успешно обновленно. Группа %s
    unknown_command: Неизвестная команда
  errors:
    default: Неизвестная ошибка
    invalid_group: Ошибка! Неизвестная группа.
    group_not_found: Группа не найдена
    message_outdated: Сообщение устарело
data:
  rings:
  - '9:30 - 11:05'
  - '11:15 - 12:50'
  - '13:35 - 15:10'
  - '15:20 - 16:55'
  lecturers:
    - &L1 Абрамян Генадий Владимирович
    - &L2 Кардакова Мария Владимировна
    - &L3 Ястребов Михаил Юрьевич
    - &L4 Бурлов Вячеслав Георгиевич
    - &L5 Васильев Евгений Владимирович
    - &L6A Шипунов Илья Сергеевич
    - &L6B Мамунц Давид Гарикович
    - &L7A Зуров Евгений Владимирович
    - &L7B Кубенский Михаил Николаевич
    - &L8 Рыданов Анатолий Александрович
    - &L9 Яландаева Мария Владимировна
    - &L10 ""
  classes:
    - &C1 Мировые ИС
    - &C2 Гуманитарные аспекты ИБ
    - &C3 Алгоритмы
    - &C4 Теоретические основы КБ
    - &C5 Физ-ра
    - &C6 Компьютерная графика
    - &C7 Дискретная математика
    - &C8 Организационное и правовое обеспечение ИБ
    - &C9 Иностранный язык
    - &C10 Правоведение
  controls:
    - Экзамен
    - Экзамен + реферат
    - Зачет + ргз
    - Экзамен
    - Зачет
    - Зачет + 2 ргз
    - Экзамен + 2 ргз
    - Зачет
    - Экзамен
    - Зачет + реферат
  timetable:
    ИЗ-21-1:
      # Понедельник
      monday:
        - [[*C1,  Лекция,   370, *L1],[*C10, Лекция, 440, *L10]]  # Первая пара
        - [[*C2,  Лекция,   440, *L2]]                            # Вторая пара
        - [[*C1,  Практика, 428, *L1]]                            # Третья пара
        - [[*C3,  Практика, 369, *L3]]                            # Четвертая пара
      # Вторник
      tuesday:
        - [[*C4,  Лекция,   472,          *L4]]                               # Первая пара
        - [[*C4,  Практика, 472,          *L4], [*C10, Практика, 307, *L10]]  # Вторая пара
        - [[*C5,  Практика, "Спорт зал",  *L5]]                               # Третья пара
      # Среда
      wednesday:
        - [[*C6,  Практика, 361, *L6A]]    # Первая пара
        - [[*C3,  Лекция,   352, *L3]]     # Вторая пара
      # Четверг
      thursday:
        - [[*C7,  Практика, 473, *L7A]]    # Первая пара
        - [[*C2,  Практика, 170, *C2]]     # Вторая пара
        - [[*C7,  Лекция,   472, *L7A]]    # Третья пара
      # Пятница
      friday:
        - [[*C5, Практика, "Спорт зал", *L5]]   # Первая пара
        - [[*C6, Лекция,   442,         *L6A]]  # Вторая пара
        - [[*C9, Практика, "",          *L9]]   # Третья пара
      # Суббота
      saturday:
        - [[*C8, Лекция, 472, *L8]] # Первая пара
    ИЗ-21-2:
      # Понедельник
      monday:
        - [[*C1,  Лекция,   370, *L1], [*C10,  Лекция,  440, *L10]] # Первая пара
        - [[*C2,  Лекция,   440, *L2]]                              # Вторая пара
        - [[*C2,  Практика, 170, *L2]]                              # Третья пара
      # Вторник
      tuesday:
        - [[*C4,  Лекция,   472,         *L4]]                              # Первая пара
        - [[*C4,  Практика, 472,         *L4],[*C10, Практика, 307, *L10]]  # Вторая пара
        - [[*C5,  Практика, "Спорт зал", *L5]]                              # Третья пара
      # Среда
      wednesday:
        - [[*C3,  Практика, 473,     *L3]]  # Первая пара
        - [[*C3,  Лекция,   352,     *L3]]  # Вторая пара
        - [[*C7,  Практика, 453/303, *L7B]] # Третья пара
      # Четверг
      thursday:
        - [["Пар нет",  "", "", ""]]       # Первая пара
        - [[*C1,  Практика, 383, *L1]]     # Вторая пара
        - [[*C7,  Лекция,   472, *L7A]]    # Третья пара
      # Пятница
      friday:
        - [[*C5, Практика, "Спорт зал", *L5]]   # Первая пара
        - [[*C6, Лекция,   472,         *L6A]]  # Вторая пара
        - [[*C9, Практика, "",          *L9]]   # Третья пара
        - [[*C6, Практика, 473,         *L6A]]  # Четвертая пара
      # Суббота
      saturday:
        - [[*C8, Лекция, 472, *L8]] # Первая пара
    ИЗ-22-1:
      # Понедельник
      monday:
        - [[*C1,  Лекция,   370, *L1], [*C10, Лекция, 440, *L10]] # Первая пара
        - [[*C2,  Лекция,   440, *L2]]                            # Вторая пара
        - [[*C9,  Практика, "",  *L9]]                            # Третья пара
        - [[*C1,  Практика, 428, *L1]]                            # Четвертая пара
      # Вторник
      tuesday:
        - [[*C4,  Лекция,   472,          *L4]]                               # Первая пара
        - [[*C10, Практика, 307,          *L10], [*C4,  Практика, 472, *L4]]  # Вторая пара  
        - [[*C5,  Практика, "Спорт зал",  *L5]]                               # Третья пара
      # Среда
      wednesday:
        - [["Пар нет",  "", "", ""]]       # Первая пара
        - [[*C3,  Лекция,   352, *L3]]     # Вторая пара
        - [[*C6,  Практика, 361, *L6A]]    # Вторая пара
        - [[*C3,  Практика, 473, *L3]]     # Четвертая пара
      # Четверг
      thursday:
        - [[*C2,  Практика, 170, *L2]]    # Первая пара
        - [[*C7,  Практика, 472, *L7A]]   # Вторая пара
        - [[*C7,  Лекция,   472, *L7A]]   # Третья пара
      # Пятница
      friday:
        - [[*C5, Практика, "Спорт зал", *L5]] # Первая пара
        - [[*C6, Лекция,   442,        *L6A]] # Вторая пара
      # Суббота
      saturday:
        - [[*C8, Лекция, 472, *L8]]        # Первая пара
    ИЗ-22-2:
      # Понедельник
      monday:
        - [[*C1,  Лекция,   370, *L1], [*C10, Лекция, 440, *L10]] # Первая пара
        - [[*C2,  Лекция,   440, *L2]]                            # Вторая пара
        - [[*C9,  Практика, "",  *L9]]                            # Третья пара
        - [[*C2,  Практика, 170, *L2]]                            # Четвертая пара
      # Вторник
      tuesday:
        - [[*C4,  Лекция,   472,          *L4]]                               # Первая пара
        - [[*C10, Практика, 307,          *L10], [*C4,  Практика, 472, *L4]]  # Вторая пара  
        - [[*C5,  Практика, "Спорт зал",  *L5]]                               # Третья пара
      # Среда
      wednesday:
        - [["Пар нет",  "", "", ""]]    # Первая пара
        - [[*C3,  Лекция,   352, *L3]]  # Вторая пара
        - [[*C3,  Практика, 473, *L3]]  # Третья пара
      # Четверг
      thursday:
        - [[*C1,  Практика, 383, *L1]]    # Первая пара
        - [[*C7,  Практика, 428, *L7B]]   # Вторая пара
        - [[*C7,  Лекция,   472, *L7A]]   # Третья пара
      # Пятница
      friday:
        - [[*C5, Практика, "Спорт зал", *L5]]   # Первая пара
        - [[*C6, Лекция,   442,         *L6A]]  # Вторая пара
        - [[*C6, Практика, 473,         *L6A]]  # Третья пара
      # Суббота
      saturday:
        - [[*C8, Лекция, 472, *L8]]   # Первая пара